--======= PART B: ROLE-BASED ACCESS CONTROL (RBAC) ========

-- CREATING CUSTOM ENTERPRISE ROLES
CREATE ROLE SalesRole;
CREATE ROLE HRRole;
CREATE ROLE DBA_Role;
GO
 
-- ASSIGNING IMPLICIT SCHEMA PRIVILEGES
GRANT SELECT, INSERT, UPDATE ON SCHEMA::Sales TO SalesRole;
DENY SELECT ON SCHEMA::HumanResources TO SalesRole;

GRANT SELECT, INSERT, UPDATE ON SCHEMA::HumanResources TO HRRole;
DENY SELECT ON SCHEMA::Sales TO HRRole;

GRANT CONTROL ON DATABASE::AdventureWorks2022 TO DBA_Role;
GO

-- SECURITY ISOLATION BOUNDARIES (LOGINS & USERS)
-- Note: Passwords are encrypted configurations in target environments
CREATE LOGIN SalesUserLogin WITH PASSWORD = 'SalesUserSecurePass123!';
CREATE LOGIN HRUserLogin WITH PASSWORD = 'HRUserSecurePass123!';
CREATE LOGIN DBAUserLogin WITH PASSWORD = 'DBAUserSecurePass123!';
GO

CREATE USER SalesUser FOR LOGIN SalesUserLogin;
CREATE USER HRUser FOR LOGIN HRUserLogin;
CREATE USER DBAUser FOR LOGIN DBAUserLogin;
GO

-- MAP INTERNAL ROLES
ALTER ROLE SalesRole ADD MEMBER SalesUser;
ALTER ROLE HRRole ADD MEMBER HRUser;
ALTER ROLE DBA_Role ADD MEMBER DBAUser;
GO

--======= END SECURITY ROLES FRAMEWORK ==========
